steps:
  # Build the main application image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/quiz-app:$COMMIT_SHA', '.']
  # Build the celery worker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/quiz-app-celery:$COMMIT_SHA', '-f', 'Dockerfile.celery', '.']
  # Push the main image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/quiz-app:$COMMIT_SHA']
  # Push the celery image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/quiz-app-celery:$COMMIT_SHA']
  # Deploy main application to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'quiz-app'
      - '--image'
      - 'gcr.io/$PROJECT_ID/quiz-app:$COMMIT_SHA'
      - '--region'
      - 'europe-north1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--add-cloudsql-instances'
      - 'YOUR_INSTANCE_CONNECTION_NAME'
      - '--set-secrets=DATABASE_URL=django_settings:latest'
  # Deploy Celery worker to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'quiz-app-celery'
      - '--image'
      - 'gcr.io/$PROJECT_ID/quiz-app-celery:$COMMIT_SHA'
      - '--region'
      - 'europe-north1'
      - '--platform'
      - 'managed'
      - '--no-allow-unauthenticated'
      - '--add-cloudsql-instances'
      - 'YOUR_INSTANCE_CONNECTION_NAME'
      - '--set-secrets=DATABASE_URL=django_settings:latest'
images:
  - 'gcr.io/$PROJECT_ID/quiz-app:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/quiz-app-celery:$COMMIT_SHA'