# Generated by Django 5.2.3 on 2025-06-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.URLField(blank=True, help_text='Opcjonalny link URL do obrazka powiązanego z pytaniem.', max_length=1024, null=True),
        ),
    ]
