# Generated by Django 5.2.3 on 2025-07-23 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Unikalna nazwa dla promptu, np. 'default_grading_prompt'", max_length=100, unique=True)),
                ('prompt_text', models.TextField(help_text='Szablon promptu. Użyj {zmiennych} dla dynamicznych danych.')),
                ('is_active', models.BooleanField(default=True, help_text='Oznacz, czy ten prompt jest obecnie aktywny.')),
            ],
            options={
                'verbose_name': 'Konfiguracja Promptu',
                'verbose_name_plural': 'Konfiguracje Promptów',
            },
        ),
    ]
