# Generated by Django 5.0.7 on 2025-07-23 20:14

from django.db import migrations

DEFAULT_PROMPT_TEXT = """
Jesteś precyzyjnym i surowym nauczycielem oceniającym odpowiedź na pytanie w quizie. Twoim zadaniem jest ocenić odpowiedź użytkownika, bazując na podanych kryteriach oceniania.

Oto szczegóły:
1. Pytanie: "{question_text}"
2. Kryteria Oceniania: "{grading_criteria}"
3. Maksymalna liczba punktów do zdobycia za to pytanie: {max_points}
4. Odpowiedź Użytkownika: "{user_answer}"

Twoje zadania:
- Oceń, w jakim stopniu odpowiedź użytkownika spełnia kryteria oceniania.
- Przyznaj liczbę punktów od 0 do {max_points}. Bądź sprawiedliwy, ale wymagający. Nie przyznawaj punktów, jeśli odpowiedź nie odnosi się do kryteriów. Nie odejmuj punktów za błędy ortograficzne, gramatyczne czy stylistyczne, chyba że są one kluczowe dla zrozumienia odpowiedzi.
- Napisz krótkie, jedno- lub dwuzdaniowe uzasadnienie swojej oceny w języku polskim, wyjaśniając, dlaczego przyznałeś tyle punktów (np. co było dobrze, a czego zabrakło).

Zwróć swoją ocenę jako idealnie sformatowany obiekt JSON. Bez żadnych dodatkowych znaków, komentarzy czy formatowania markdown. JSON musi zawierać DOKŁADNIE dwa klucze: "score" (typu integer) i "feedback" (typu string).
"""

def create_default_prompt(apps, schema_editor):
    PromptConfiguration = apps.get_model('api_v1', 'PromptConfiguration')
    # Używamy update_or_create, aby uniknąć błędu, jeśli prompt już istnieje.
    # To sprawia, że migracja jest idempotentna (można ją uruchamiać wielokrotnie).
    PromptConfiguration.objects.update_or_create(
        name='default_grading_prompt',
        defaults={
            'prompt_text': DEFAULT_PROMPT_TEXT,
            'is_active': True
        }
    )

def delete_default_prompt(apps, schema_editor):
    PromptConfiguration = apps.get_model('api_v1', 'PromptConfiguration')
    PromptConfiguration.objects.filter(name='default_grading_prompt').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0002_promptconfiguration'),
    ]

    operations = [
        migrations.RunPython(create_default_prompt, delete_default_prompt),
    ]
