# Generated by Django 5.2.3 on 2025-07-14 01:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0002_question_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportedIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issue_type', models.CharField(choices=[('QUESTION_ERROR', 'Błąd w pytaniu/odpowiedzi'), ('AI_GRADING_ERROR', 'Niesłuszna ocena AI')], help_text='Typ zgłoszonego problemu.', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Opcjonalny opis problemu od użytkownika.', null=True)),
                ('ai_feedback_snapshot', models.TextField(blank=True, help_text="Zapisana odpowiedź AI w momencie zgłoszenia (dla zgłoszeń typu 'AI_GRADING_ERROR').", null=True)),
                ('status', models.CharField(choices=[('NEW', 'Nowe'), ('IN_PROGRESS', 'W trakcie analizy'), ('RESOLVED', 'Rozwiązane'), ('REJECTED', 'Odrzucone')], default='NEW', help_text='Aktualny status zgłoszenia.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data i czas utworzenia zgłoszenia.')),
                ('question', models.ForeignKey(help_text='Pytanie, którego dotyczy zgłoszenie.', on_delete=django.db.models.deletion.CASCADE, related_name='reported_issues', to='api_v1.question')),
                ('test', models.ForeignKey(help_text='Test, w którym wystąpiło zgłoszenie.', on_delete=django.db.models.deletion.CASCADE, related_name='reported_issues', to='api_v1.test')),
            ],
            options={
                'verbose_name': 'Zgłoszony Problem',
                'verbose_name_plural': 'Zgłoszone Problemy',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['question'], name='reported_issue_question_idx'), models.Index(fields=['test'], name='reported_issue_test_idx'), models.Index(fields=['status'], name='reported_issue_status_idx')],
            },
        ),
    ]
