# Generated by Django 5.2.3 on 2026-03-27 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0004_quizsession_questionattempt'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='questionattempt',
            new_name='api_v1_ques_user_id_a01de0_idx',
            old_name='attempt_user_question_idx',
        ),
        migrations.RenameIndex(
            model_name='questionattempt',
            new_name='api_v1_ques_user_id_710e38_idx',
            old_name='attempt_user_sr_next_idx',
        ),
        migrations.RenameIndex(
            model_name='questionattempt',
            new_name='api_v1_ques_session_111456_idx',
            old_name='attempt_session_idx',
        ),
        migrations.RenameIndex(
            model_name='questionattempt',
            new_name='api_v1_ques_answere_c7109b_idx',
            old_name='attempt_answered_at_idx',
        ),
        migrations.RenameIndex(
            model_name='quizsession',
            new_name='api_v1_quiz_user_id_2d96b5_idx',
            old_name='quizsession_user_started_idx',
        ),
    ]
